version: '3'
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/volumes/portainer-ce:/data
    ports:
    #- 9443:9443
    - 9000:9000
    restart: unless-stopped